using System;

public class Emotions
{
    List<string> emotions = new List<string>
{
    "great sorrow",
    "anguish",
    "joy",
    "happiness",
    "delight",
    "ecstasy",
    "euphoria",
    "bliss",
    "contentment",
    "satisfaction",
    "gratitude",
    "relief",
    "hope",
    "optimism",
    "excitement",
    "enthusiasm",
    "anticipation",
    "wonder",
    "awe",
    "admiration",
    "love",
    "affection",
    "fondness",
    "tenderness",
    "adoration",
    "devotion",
    "compassion",
    "empathy",
    "sympathy",
    "trust",
    "belonging",
    "connection",
    "pride",
    "confidence",
    "courage",
    "determination",
    "inspiration",
    "amusement",
    "playfulness",
    "curiosity",
    "fascination",
    "interest",
    "serenity",
    "peace",
    "calm",
    "tranquility",
    "nostalgia",
    "longing",
    "yearning",
    "desire",
    "passion",
    "infatuation",
    "attraction",
    "envy",
    "jealousy",
    "resentment",
    "bitterness",
    "hatred",
    "loathing",
    "disgust",
    "contempt",
    "anger",
    "rage",
    "fury",
    "irritation",
    "annoyance",
    "frustration",
    "exasperation",
    "agitation",
    "impatience",
    "indignation",
    "betrayal",
    "disappointment",
    "discouragement",
    "despair",
    "hopelessness",
    "helplessness",
    "grief",
    "mourning",
    "sadness",
    "sorrow",
    "melancholy",
    "misery",
    "loneliness",
    "isolation",
    "emptiness",
    "heartbreak",
    "regret",
    "remorse",
    "guilt",
    "shame",
    "embarrassment",
    "humiliation",
    "insecurity",
    "self-doubt",
    "inferiority",
    "fear",
    "terror",
    "horror",
    "dread",
    "panic",
    "anxiety",
    "worry",
    "apprehension",
    "nervousness",
    "unease",
    "uncertainty",
    "confusion",
    "bewilderment",
    "perplexity",
    "disbelief",
    "shock",
    "surprise",
    "astonishment",
    "amazement",
    "suspicion",
    "distrust",
    "skepticism",
    "ambivalence",
    "indifference",
    "apathy",
    "boredom",
    "weariness",
    "exhaustion",
    "overwhelm",
    "vulnerability",
    "insecurity",
    "exposure",
    "alienation",
    "disconnection",
    "resignation",
    "acceptance",
    "forgiveness",
    "reconciliation",
    "reluctance",
    "hesitation",
    "doubt",
    "conflict",
    "tension",
    "anticipation",
    "eagerness",
    "urgency",
    "impatience",
    "satisfaction",
    "triumph",
    "victory",
    "accomplishment",
    "fulfillment",
    "empowerment",
    "liberation",
    "freedom",
    "reassurance",
    "security",
    "safety",
    "warmth",
    "comfort",
    "affection",
    "appreciation",
    "respect",
    "reverence",
    "humility",
    "shyness",
    "awkwardness",
    "timidity",
    "cautiousness",
    "wariness",
    "defensiveness",
    "possessiveness",
    "protectiveness",
    "sympathy",
    "pity",
    "compassion",
    "kindness",
    "generosity",
    "altruism",
    "satisfaction",
    "pride",
    "vanity",
    "arrogance",
    "superiority",
    "inferiority",
    "ambition",
    "motivation",
    "drive",
    "persistence",
    "resilience",
    "perseverance",
    "defeat",
    "failure",
    "humiliation",
    "desperation",
    "franticness",
    "restlessness",
    "agitation",
    "irritability",
    "hostility",
    "aggression",
    "vengeance",
    "vindictiveness",
    "malice",
    "cruelty",
    "spite",
    "schadenfreude",
    "reluctant hope",
    "bittersweetness",
    "melancholy",
    "wistfulness",
    "sentimentality",
    "yearning",
    "homesickness",
    "estrangement",
    "loss",
    "grief",
    "devastation",
    "desolation",
    "despair",
    "anguish",
    "torment",
    "agony",
    "suffering",
    "distress",
    "affliction",
    "desperation",
    "terror",
    "existential dread",
    "paranoia",
    "foreboding",
    "ominous anticipation",
    "relief",
    "reassurance",
    "renewed hope",
    "optimism",
    "faith",
    "trust",
    "wonder",
    "reverence",
    "transcendence",
    "spiritual awe",
    "inner peace",
    "serenity",
    "contentment",
    "acceptance",
    "gratitude",
    "joyful anticipation",
    "ecstatic joy",
    "overwhelming happiness",
    "quiet happiness",
    "profound sadness",
    "deep loneliness",
    "crushing disappointment",
    "burning anger",
    "consuming hatred",
    "paralyzing fear",
    "overwhelming anxiety",
    "deep affection",
    "unconditional love",
    "profound gratitude",
    "bittersweet nostalgia",
    "quiet melancholy",
    "restless curiosity",
    "intense fascination",
    "overwhelming awe",
    "guilty pleasure",
    "moral outrage",
    "righteous indignation",
    "quiet resentment",
    "suppressed anger",
    "hidden sadness",
    "repressed fear",
    "guarded optimism",
    "cautious hope",
    "desperate longing",
    "unrequited love",
    "forbidden desire",
    "shattered trust",
    "betrayed affection",
    "emotional exhaustion",
    "numbness",
    "emotional detachment",
    "emptiness",
    "inner turmoil",
    "emotional conflict",
    "quiet desperation",
    "overwhelming relief",
    "unexpected joy",
    "bittersweet joy",
    "triumphant exhilaration"
};
    public string EmotionalState()
    {
        Random random = new Random();
        return this.emotions[random.Next(this.emotions.Count)];
    }
}
